"""Generate the headers and compile-check them with devkitARM's g++.

Headers are generated by the repository's `make` into <repo>/include. The check
is the local equivalent of `make verify`, except that it targets the real
3DS ABI (ARMv6K, hard float) instead of `-m32`, needs no cmake, and can also
assert the offset and size of every single member, not just sizeof(class).
"""
import re
import subprocess

from .. import paths
from . import templates

DEFAULT_VERSION = "VERSION_USA_REV1"  # same as CMakeLists.txt


def versions() -> list[str]:
    text = (paths.TEMPLATE_DIR / "versions.h").read_text()
    return re.findall(r"^#define\s+(VERSION_\w+)\s+\d+", text, re.M)


def normalize_version(v: str) -> str:
    v = v.upper()
    if not v.startswith("VERSION_"):
        v = "VERSION_" + v
    if v not in versions():
        raise SystemExit(f"unknown version {v}; known: {', '.join(versions())}")
    return v


def generate() -> int:
    """Render the templates with the repository's own `make`.

    <repo>/template goes to <repo>/include; a work copy (--templates) goes to
    the `include` folder next to it. Returns the number of files rewritten.
    """
    proc = subprocess.run(["make", "-C", str(paths.REPO), f"SOURCES={paths.TEMPLATE_DIR}", f"BUILD={paths.INCLUDE_DIR}"],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit((proc.stdout + proc.stderr).strip() or "make failed")
    return sum(1 for line in proc.stdout.splitlines() if line.startswith("Processing "))


def _write_all_headers():
    paths.VERIFY_DIR.mkdir(parents=True, exist_ok=True)
    headers = sorted(str(p.relative_to(paths.INCLUDE_DIR)) for p in paths.INCLUDE_DIR.rglob("*.hpp"))
    (paths.VERIFY_DIR / "all_headers.hpp").write_text(
        "// Auto-generated - do not edit\n" + "".join(f'#include "{h}"\n' for h in headers))


def _offset_asserts(index: templates.Index, namespace: str | None) -> tuple[str, int]:
    prefix = f"{namespace}::" if namespace else ""
    templated = {c.qualname for c in index.classes if c.template}
    seen = set()
    lines = ['#include <cstddef>', '#include "all_headers.hpp"', ""]
    count = 0
    for c in index.classes:
        parts = c.qualname.split("::")
        enclosing = {"::".join(parts[:i]) for i in range(1, len(parts) + 1)}
        # Skip what cannot be named unconditionally: templates, version-specific
        # classes, and classes declared twice (one per version).
        if enclosing & templated or c.conditional or c.qualname in seen:
            continue
        if sum(1 for o in index.classes if o.qualname == c.qualname) > 1:
            continue
        seen.add(c.qualname)
        rel = paths.rel(c.file)
        for m in c.members:
            if m.kind == "gap" or m.conditional or m.bitfield:
                continue
            q = f"{prefix}{c.qualname}"
            where = f"{rel}:{c.line} {c.qualname}::{m.name}"
            lines.append(f'static_assert(offsetof({q}, {m.name}) == 0x{m.offset:X}, "OFFSET {where} declared 0x{m.offset:X}");')
            lines.append(f'static_assert(sizeof({q}::{m.name}) == 0x{m.size:X}, "SIZE {where} declared 0x{m.size:X}");')
            count += 1
    return "\n".join(lines) + "\n", count


def compile_check(version: str = DEFAULT_VERSION, namespace: str | None = None,
                  offsets: bool = False, index: templates.Index | None = None) -> tuple[bool, str]:
    _write_all_headers()
    source = paths.VERIFY_DIR / "all_headers.hpp"
    extra = []
    if offsets:
        text, _ = _offset_asserts(index or templates.Index(), namespace)
        source = paths.VERIFY_DIR / "offsets.cpp"
        source.write_text(text)
        extra = ["-fno-access-control", "-Wno-invalid-offsetof"]
    cmd = [
        paths.arm_tool("g++"), "-std=c++23", "-fsyntax-only", "-x", "c++",
        "-march=armv6k", "-mtune=mpcore", "-mfloat-abi=hard", "-mtp=soft",
        "-fdiagnostics-color=never", "-fmax-errors=200",
        "-DNNSDK", f"-DGAME_VERSION={version}",
        f"-I{paths.DEVKITPRO / 'libctru' / 'include'}",
        f"-I{paths.INCLUDE_DIR}", f"-I{paths.VERIFY_DIR}",
    ]
    if namespace:
        cmd.append(f"-DMK7MEMORY_NAMESPACE={namespace}")
    for inc in ("sead/include", "nnheaders/include", "nw4c/include", "libc/include", "lms/Include"):
        cmd += ["-isystem", str(paths.VENDOR_DIR / inc)]
    cmd += extra + [str(source)]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    out = proc.stderr.replace(str(paths.REPO) + "/", "")
    out = "\n".join(l for l in out.splitlines() if "#pragma once in main file" not in l)
    return proc.returncode == 0, out


def summarize(output: str, limit: int = 40) -> str:
    """Keep the lines that matter from a g++ error dump."""
    keep = []
    lines = output.splitlines()
    for i, line in enumerate(lines):
        if "error:" in line or "fatal error" in line:
            keep.append(line)
            # g++ prints the evaluated comparison a few lines below the assert.
            for follow in lines[i + 1:i + 6]:
                if "comparison reduces to" in follow:
                    keep.append("    " + follow.strip())
                    break
    if len(keep) > limit:
        keep = keep[:limit] + [f"... {len(keep) - limit} more lines"]
    return "\n".join(keep)
